/**
 * Generates src/environments/environment.ts from environment variables.
 *
 * Values are read from process.env first (so CI secrets win) and fall back to a
 * local `.env` file at the repo root. The generated file is gitignored — never
 * commit credentials. Use the Supabase ANON public key, never the service_role.
 *
 * Runs automatically via the `config`, `prestart`, `prebuild` and `postinstall`
 * npm scripts.
 */
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const envFile = path.join(root, '.env');
const target = path.join(root, 'src', 'environments', 'environment.ts');

/** Minimal .env parser (no external dependency). */
function parseEnvFile(file) {
  if (!fs.existsSync(file)) return {};
  const result = {};
  for (const rawLine of fs.readFileSync(file, 'utf8').split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

const fromFile = parseEnvFile(envFile);
const supabaseUrl = process.env.SUPABASEURL ?? fromFile.SUPABASEURL ?? '';
const supabaseKey = process.env.SUPABASEKEY ?? fromFile.SUPABASEKEY ?? '';

if (!supabaseUrl || !supabaseKey) {
  console.warn(
    '[set-env] WARNING: SUPABASEURL / SUPABASEKEY missing. ' +
      'Create a .env file at the repo root (see .env.example) or set them as env vars.',
  );
}

const contents = `// AUTO-GENERATED by scripts/set-env.js — do not edit, do not commit.
// Source: .env (local) or CI secrets. Use the Supabase ANON key, never service_role.
export const environment = {
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseKey: ${JSON.stringify(supabaseKey)},
};
`;

fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, contents);
console.log(`[set-env] Wrote ${path.relative(root, target)}`);
